= JHH6 Dokumentation (C) 2018 cwkuehl.de
Wolfgang Kühl <wolfgang@cwkuehl.de>
v1.0, 2018-01-26
:homepage: http://cwkuehl.de
:toc2:
:icons: font
:data-uri:
:imagesdir: ../de/assets
////
Bilder einbetten bzw. separat
:imagesdir: de/assets
////
:doctype: book
:lang: de
:toc-title: Inhaltsverzeichnis
:note-caption: Anmerkung
:warning-caption: Achtung
:tip-caption: Tipp

== Beste Funktionen

Das Haushalts-Programm enthält eine Sammlung von Funktionen und Dialogen, die fast jeder verwenden kann:

- *Haushaltsführung* mit doppelter Buchführung, Eröffnungs- und Schlussbilanz sowie Gewinn- und Verlustrechnung (Bereich Haushalt)
- *Adressenverwaltung* mit beliebig vielen Adressen pro Person und Geburtstagsliste beim Start (Bereich Privat)
- *Tagebuch* speichert pro Tag einen beliebig langen Text (Bereich Privat)
- *Stammbaum* mit Ahnen, Familien, Quellen und GEDCOM-Schnittstelle (Bereich Stammbaum)
- *Heilpraktiker*-Praxis mit Erfassen von Patienten, Behandlungen und Rechnungen (Bereich Heilpraktiker)
- *Wertpapiere* mit Point and Figure-Charts (Bereich Wertpapiere)
- *Messdienerordnungen* erstellen (Bereich Messdiener)


== Installation

Generell wird eine aktuelle Java-Installation vorausgesetzt.

Herunterladen der zum Betriebsystem passenden Batch-Datei von http://cwkuehl.de/jhh6[JHH6 Download].

=== Installation für Windows
- Speichern der Batch-Datei als #InstallUpdateJhh6.cmd in einem leeren Verzeichnis, z.B. D:\Haushalt\JHH6.

TIP: Dazu ist es notwendig, dass die Dateiendungen angezeigt werden.
In Windows erreicht man die Einstellung über den Windows Explorer, im Bereich Datei, Optionen die Auswahl ‚Ordner- und Suchoptionen ändern‘.
Hier muss im Tab Ansicht der Haken bei der Einstellung ‚Erweiterungen bei bekannten Dateitypen ausblenden‘ entfernt werden.

- Starten von cmd.exe.
- Wechseln in das Verzeichnis:
----
 D:
 cd \Haushalt\JHH6
----
- Ausführen der Datei:
----
 #InstallUpdateJhh6.cmd
----
- Beim nächsten Mal starten mit:
----
 #JHH6.cmd
----

=== Installation für Linux
.(getestet für Ubuntu 16.04)
- Speichern der Batch-Datei als #InstallUpdateJhh6.sh in einem leeren Verzeichnis, z.B. /opt/Haushalt/JHH6.
- Starten einer Terminal-Sitzung.
- Wechseln in das Verzeichnis und Ausführungsberechtigung setzen:
----
 cd /opt/Haushalt/JHH6
 chmod 755 #InstallUpdateJhh6.sh
----
- Ausführen der Datei:
----
 ./#InstallUpdateJhh6.sh
----
- Beim nächsten Mal starten mit:
----
 ./#JHH6.sh
----

== Starten des Programms

=== Starten für Windows
Ausführen der Datei:
----
 #JHH6.cmd
----
im Installtionsverzeichnis.

=== Starten für Linux
Ausführen der Datei:
----
 ./#JHH6.sh
----
im Installtionsverzeichnis.

=== Erste Anmeldung
Beim ersten Starten des Programms wird die Benutzer-ID und das Kennwort des Administrator-Benutzers festgelegt.
Den Eintrag 1 beim Mandanten sollte nicht geändert werden. Die Felder Benutzer und Kennwort müssen mit den gewünschten
Werten gefüllt werden, bevor die Schaltfläche Anmelden betätigt werden kann. Siehe auch <<AM000>>.


== Benutzer-Oberfläche

Nach dem Starten öffnet sich das Hauptfenster. Es ist in die vier Bereiche unterteilt: Titelzeile, Menü, Formulare, Statuszeile.
Das Hauptfenster lässt sich beliebig positionieren und in der Größe ändern. Beim nächsten Starten erscheint das Hauptfenster an der
gleichen Stelle in der gleichen Größe.

=== Titelzeile
.In der Titelzeile wird der Name des Programms mit zusätzlichen Informationen angezeigt:
- Falls das Programm in Testmodus gestartet wurde, beginnt die Zeile mit dem Text "Test-".
- Falls noch kein Benutzer angemeldet ist, wird dies mit dem Text "(nicht angemeldet)" am Ende angezeigt.
- Falls ein Benutzer mit einem anderen Mandanten als 1 angemeldet ist, wird dies am Ende der Titelzeile angezeigt, z.B. "(Mandant 2)". 

=== Menü-Bereich
Im Menü werden alle aktuell verfügbaren Menüpunkte angezeigt. Die meisten Menüpunkte sind erst nach der Anmeldung sichtbar.
Mit den Einstellungen lassen sich einige Hauptmenüpunkt komplett aus- bzw. einblenden.

=== Formular-Bereich
In diesem Tabulator-Bereich wird immer höchstens ein Formular angezeigt. Wenn mehrere Formulare offen sind, kann mit Hilfe der
Tabulator-Köpfe eines auswählen. Über das X nach dem Formulartitel kann ein Formular geschlossen werden.

=== Statuszeile
Hier werden Hinweise oder Fehlermeldungen angezeigt.


== Menü

Das Menü umfasst folgende Punkte:

[width="100%",cols="<1,<1,<4",frame="all",options="header"]
|==========================
|Menü|Menüpunkt|Erklärung
.2+|Datei    |                   |Aufruf der Funktionen und Dialoge aus dem Bereich Datei.
             |Beenden            |Das Programm wird ohne Nachfrage beendet.
.2+|Benutzer |                   |Aufruf der Funktionen und Dialoge aus dem Bereich Benutzer.
             |Anmelden / Abmelden|Dialog zum Anmelden, falls dies noch nicht geschehen ist. Abmelden, wenn man angemeldet ist.
|==========================

Kennwort ändern
Dialog zum Ändern des Kennworts.

Einstellungen
Dialog zum Ändern von Einstellungen.

Start-Dialoge
Dialog zum Auswählen von Dialogen, die nach dem Anmelden geöffnet werden.
Privat

Aufruf der Funktionen und Dialoge aus dem Bereich Privat.

Tagebuch
Dieser Dialog verwaltet beliebig lange textliche Eintragungen für jeden Tag.

Notizen
Dieser Dialog verwaltet beliebig lange Notizen in Text- und Tabellenform für jede Gelegenheit.

Adressen
Dieser Dialog verwaltet Personen, Geburtstage und Adressen.

Fahrradstände
Dieser Dialog verwaltet Fahrrad-Touren und Fahrradstände.

Fahrräder
Dieser Dialog verwaltet Fahrräder.

Bücher
Dieser Dialog verwaltet Bücher.

Autoren
Dieser Dialog verwaltet Buch-Autoren.

Serien
Dieser Dialog verwaltet Buch-Serien.

Lektionen
Dieser Dialog verwaltet Lektionen.

Lektioninhalte
Dieser Dialog verwaltet Lektioninhalte.

Statistik
Dieser Dialog zeigt eine Übersicht über verschiedene Informationen, die im Programm erfasst sind.
Haushalt

Aufruf der Funktionen und Dialoge aus dem Bereich Haushalt.

Buchungen
Mit diesem Dialog können Sie komfortabel alle möglichen Buchungen erfassen, kopieren, ändern und stornieren.

Ereignisse
Dieser Dialog erlaubt das Bearbeiten von Ereignissen, also vorgefertigten Buchungen.

Konten
Dieser Dialog dient der Verwaltung der Konten. Hier können die Konten angezeigt, erstellt, geändert und eingeschränkt gelöscht werden.

Perioden
Mit diesem Dialog werden die Perioden bearbeitet.

Schlussbilanz
In diesem Dialog wird die Schlussbilanz (SB) als T-Konto dargestellt.

G+V-Rechnung
In diesem Dialog wird die Gewinn- und Verlustrechnung (GV) als T-Konto dargestellt.

Eröffnungsbilanz
In diesem Dialog wird die Eröffnungsbilanz (EB) als T-Konto dargestellt.
Vermietung

Aufruf der Funktionen und Dialoge aus dem Bereich Vermietung.

VM-Buchungen
Mit diesem Dialog können Sie komfortabel alle möglichen Vermietungs-Buchungen erfassen, kopieren, ändern und stornieren.

VM-Ereignisse
Dieser Dialog erlaubt das Bearbeiten von Vermietungs-Ereignissen, also vorgefertigten Buchungen.

VM-Konten
Dieser Dialog dient der Verwaltung der Vermietungs-Konten. Hier können die Konten angezeigt, erstellt, geändert und eingeschränkt gelöscht werden.

Perioden
Mit diesem Dialog werden die Perioden bearbeitet.

Miet-Forderungen
Dieser Dialog zeigt die Miet-Forderungen an, die nicht bezahlt wurden.

Häuser
Dieser Dialog verwaltet Häser.

Wohnungen
Dieser Dialog verwaltet Wohnungen.

Mieter
Dieser Dialog verwaltet Mieter.

Mieten
Dieser Dialog verwaltet Mieten von Wohnungen.

Haus-Abrechnungen
Dieser Dialog verwaltet Betriebskostenabrechnungen auf Häuser-Ebene.

Abrechnungen
Dieser Dialog verwaltet Betriebskostenabrechnungen in Einzel-Darstellung.
Heilpraktiker

Aufruf der Funktionen und Dialoge aus dem Bereich Heilpraktiker.

Anamnesen
Dieser Dialog verwaltet die Anamnesen der Patienten mit Symptomen.

Behandlungen
Dieser Dialog verwaltet die Behandlungen der Patienten mit Symptomen und Diagnose.

Rechnungen
Dieser Dialog verwaltet die Rechnungen für Patienten.

Patienten
Dieser Dialog verwaltet die Patienten.

Status
Dieser Dialog verwaltet die möglichen Status für Behandlungen und Rechnungen.

Leistungen
Dieser Dialog verwaltet die möglichen Leistungen für Behandlungen.

Einstellungen
Dieser Dialog verwaltet die Einstellungen für den Bereich Heilpraktiker.
Stammbaum

Aufruf der Funktionen und Dialoge aus dem Bereich Stammbaum.

Ahnen
Dieser Dialog verwaltet alle Ahnen.

Familien
Dieser Dialog verwaltet alle Ahnen-Familien.

Quellen
Dieser Dialog verwaltet die Quellen-Angaben für die Ahnen.
Wertpapiere

Aufruf der Funktionen und Dialoge aus dem Bereich Wertpapiere.

Wertpapiere
Dieser Dialog verwaltet alle Wertpapiere.

Konfigurationen
Dieser Dialog verwaltet alle Point and Figure-Konfigurationen zur Auswertung von Wertpapieren.

Wertpapier-Chart
Dieser Dialog zeigt die Kurse und das Point and Figure-Chart eines Wertpapiers.

Charts
Dieser Dialog zeigt drei Point and Figure-Charts.
Administration

Aufruf der Funktionen und Dialoge aus dem Bereich Administration.

Mandanten
Dieser Dialog verwaltet alle Mandanten in der aktuellen Datenbank.

Benutzer
Dieser Dialog verwaltet alle Benutzer des aktuellen Mandanten.

Sicherung
Dieser Dialog bietet eine einfache Durchführung von Sicherungen auf Verzeichnis-Ebene an.

Replikation
Dieser Dialog verwaltet die Replikation des aktuellen Mandanten mit einer anderen Datenbank.
Sonstiges

Aufruf der Funktionen und Dialoge aus dem Bereich Sonstiges.

Gottesdienste
Dieser Dialog verwaltet die Gottesdienste.

Messdiener
Dieser Dialog verwaltet die Messdiener.

Profile
Dieser Dialog verwaltet die Gottesdienst-Profile, d.h. Liste der Dienste mit minimaler Anzahl der Messdiener.

Einstellungen
Dieser Dialog verwaltet die Messdiener-Einstellungen.

Sudoku
Dieser Dialog erlaubt das Prüfen und Lösen von Sudoku-Rätseln.

Detektiv
Dieser Dialog erlaubt das Prüfen und Lösen von Detektiv-Rätseln.
Hilfe

Aufruf der Funktionen und Dialoge aus dem Bereich Hilfe.

Hilfe
Aufruf dieser Hilfe im eingestellten Browser.

Info
Aufruf des Dialog für Informationen über das Programm aus den Kategorien Server, Client und Anmeldung.
|==========================


== Formulare und Dialoge

Es gibt zwei verschiedene Arten von Formularen. Die erste Art wird im Formularbereich geöffnet und ist somit von der Größe an das
Hauptfenster gebunden, z.B. das Tagebuch-Formular. Die andere Art öffnet sich meist als Folgeformular der ersten Art
und kann in Größe und Position beliebig geändert werden. Die zweite Art wird als Dialog bezeichnet. Diese Dialoge behalten sich die letzte Position und Größe für das
nächste Öffnen.

.Fenster verschwunden?
NOTE: Falls einzelne Dialoge verschwunden sind, können die Positionen und Größe zurückgesetzt werden, und zwar mit dem Menüpunkt
_Benutzer_ - _Dialoge zurücksetzen_. Falls das Hauptfenster nicht mehr sichtbar ist, kann es über die Schaltfläche Zurücksetzen auf den
Hauptbildschirm zurückgeholt werden.


include::../de/am/AM000.adoc[]
